# 📘 NumPy Revision Notes

> A running set of notes, built chapter by chapter, for quick revision.

---

## Chapter 1: Why NumPy?

### 🔹 The Problem: Python Lists

Python lists are **general-purpose containers** — designed to store *any* type of Python object.

```python
data = [10, "Jagadeesh", True, 98.5, [1, 2, 3], {"age": 22}]
```

Since a list can hold mixed types, it doesn't store the actual values directly.
Instead, it stores **references (memory addresses)** pointing to separate Python objects.

**Internally, it looks like this:**

```
Python List
    │
    ├──► Integer Object (10)
    ├──► String Object ("Hello")
    ├──► Float Object (98.5)
    └──► Boolean Object (True)
```

> 💡 **Key idea:** A Python list stores *references* to objects, not the objects themselves.

---

### 🔹 Why Does Python Do This?

Because lists are built to hold **heterogeneous (mixed-type) data**:

```python
employee = [
    101,
    "Rahul",
    True,
    75000.50,
    {"department": "IT"}
]
```

Different data types coexisting in one list — that flexibility is *why* references are needed.

---

### 🔹 The Drawback

For large-scale numerical work (millions of values):

- Every element is a separate Python object.
- The list only stores references to them.
- Python processes elements one at a time.
- Result → high memory usage + high computational overhead.

---

### 🔹 The Solution: NumPy

NumPy was built for **large-scale numerical computing**.

Instead of scattering references to separate objects, NumPy stores elements of the **same data type** in one **contiguous block of memory**:

```
50000 | 60000 | 70000 | 80000 | 90000
```

This layout is far more memory-efficient and enables much faster computation.

> ### 🧠 First Principle of NumPy
> **A NumPy array stores elements of the same data type in contiguous memory.**
>
> This single idea is the foundation for everything else in NumPy.

---

### 🔹 Why Is NumPy Faster?

| Reason | Explanation |
|---|---|
| Homogeneous data | All elements share one data type |
| Contiguous memory | Data sits together in memory, not scattered |
| Less object overhead | No per-element Python object wrapping |
| C-level execution | Operations run via optimized, compiled C code |
| No Python-level loops | Loops written by the user aren't needed |

> ⚠️ **Important clarification:** NumPy does **NOT** eliminate looping altogether.
> It eliminates **Python-level** loops. Internally, NumPy still iterates over data — just using fast, compiled C code instead of slow Python bytecode.

---

### 🔹 When Should You Use NumPy?

Use NumPy when:
- ✅ Data is numerical
- ✅ All elements share the same data type
- ✅ Dataset is large
- ✅ High-performance math/computation is needed

**Real-world examples:**
- Employee salaries
- Attendance percentages
- Sales data
- Sensor readings
- Financial datasets
- Machine Learning datasets

---

### 🔑 Key Takeaways — Chapter 1

- Python lists store **references** to Python objects.
- Python lists support **heterogeneous** data.
- NumPy arrays store **homogeneous** data.
- NumPy stores data in **contiguous memory**.
- NumPy is optimized for **numerical computation**.
- NumPy removes **Python-level iteration overhead** via compiled C code (not looping itself).

---

<!-- 🔽 Chapter 2 will be added below this line -->

# NumPy - Chapter 2: ndarray (N-Dimensional Array)

## What is ndarray?

`ndarray` stands for **N-Dimensional Array**.

The **N** represents **any number of dimensions**.

NumPy uses the same data structure to represent:

- 0D (Scalar)
- 1D (Vector / List)
- 2D (Matrix / Table)
- 3D (Collection of Tables)
- ND (Higher-dimensional arrays)

---

## Dimension Hierarchy

### 0D

A single value.

Example:

```python
50000
```

---

### 1D

A sequence of values.

Example:

```python
[50000, 60000, 70000]
```

---

### 2D

Rows and columns.

Example:

```python
[
    [101, 50000],
    [102, 60000],
    [103, 70000]
]
```

---

### 3D

A collection of multiple 2D arrays.

Example:

Monthly employee salary tables.

---

## Why One Class?

NumPy uses a single class:

```python
numpy.ndarray
```

instead of creating separate classes like:

- Array1D
- Array2D
- Array3D

This provides a consistent API regardless of the number of dimensions.

---

## Data Engineering Examples

- Employee IDs → 1D
- Salary Table → 2D
- Monthly Salary Data → 3D
- Multi-year Department Data → ND

---

## Key Takeaways

- `ndarray` = N-Dimensional Array.
- The same object represents arrays of any dimension.
- Dimensions describe the structure of the data.
- Most Data Engineering tasks commonly use 1D and 2D arrays.

In [3]:
import numpy as np

# Size:

The size of an ndarray is the total number of elements in the array. It is equal to the product of the dimensions of the array.

In [4]:
# Create a 3D array
arr_3d = np.zeros((2, 3, 4))
print(arr_3d)

# Print the size
print("data type of the array : ",arr_3d.dtype)
print("Size of the array:", arr_3d.size)  # Output: 24 (2 * 3 * 4)
print("diemensions present in the given array : ",arr_3d.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
data type of the array :  float64
Size of the array: 24
diemensions present in the given array :  3


## Creating an Array from a Python List

In [6]:
import numpy as np

numbers = [10, 20, 30, 40, 50]

arr = np.array(numbers)

print(arr)
print(type(numbers))
print(type(arr))

[10 20 30 40 50]
<class 'list'>
<class 'numpy.ndarray'>


### Notice:

- It prints without commas.
- The result is not a Python list.
- It is an ndarray.

## Chapter 2: Creating NumPy Arrays
 
### 🔹 Creating an Array Directly
 
Instead of creating a Python list first and converting it, you can create a NumPy array **directly**:
 
```python
arr = np.array([10, 20, 30, 40, 50])
```
 
Both approaches (list-first vs. direct) are equivalent — `np.array()` simply takes any sequence and converts it into a NumPy array.
 
---
 
### 🔹 Creating a Float Array
 
```python
arr = np.array([10.5, 20.7, 30.2])
 
print(arr)
```
 
**Output:**
```
[10.5 20.7 30.2]
```
 
---
 
### 🔹 Creating a String Array
 
```python
arr = np.array(["HR", "IT", "Finance"])
 
print(arr)
```
 
**Output:**
```
['HR' 'IT' 'Finance']
```
 
---
 
### 🔹 Creating a Boolean Array
 
```python
arr = np.array([True, False, True])
 
print(arr)
```
 
**Output:**
```
[ True False  True]
```
 
---
 
### 🔹 Data Engineering Examples
 
These are realistic examples of where NumPy fits into a real data pipeline.
 
**Employee IDs**
```python
employee_ids = np.array([101, 102, 103, 104])
 
print(employee_ids)
```
 
**Employee Salaries**
```python
employee_salary = np.array([
    50000,
    62000,
    71000,
    54000
])
 
print(employee_salary)
```
 
**Attendance Percentage**
```python
attendance = np.array([
    98,
    87,
    92,
    95
])
 
print(attendance)
```
 
---
 
### 🔑 Key Takeaways — Chapter 2
 
- `np.array()` can create an array **directly** from a sequence — no need to build a plain list first as a separate step.
- NumPy arrays can hold **integers, floats, strings, or booleans** — but each array itself stays homogeneous (one type).
- This is the same `np.array()` function used throughout — it adapts based on the data you pass in.
- Real-world use cases (employee IDs, salaries, attendance %) show how NumPy arrays naturally represent single-type numeric/categorical columns of data — much like a column in a spreadsheet or database table.
---

## Higher Dimensional Arrays

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [9]:
import numpy as np

employees = np.array([
    "Rahul",
    "Anjali",
    "Vikram",
    "Sneha"
])

ages = np.array([
    24,
    28,
    31,
    26
])

salary = np.array([
    50000,
    62000,
    71000,
    54000
])

print(type(employees))
print(type(ages))
print(type(salary))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### np.array() always returns an object of type numpy.ndarray, regardless of the data it contains

Data Types (`dtype`)
 
**📝 Concept**
One of the biggest reasons NumPy is so fast is its **data type system**.
 
In plain Python:
```python
numbers = [10, 20, 30]
```
Every integer here is a separate Python object.
NumPy does **not** do that — it stores all values as **one fixed data type**.
 
---
 
**📝 Concept — Checking the Data Type**
Use `.dtype` to inspect what type an array is storing internally.
 
**▶️ Code Cell**
```python
import numpy as np
 
arr = np.array([10, 20, 30])
 
print(arr.dtype)
```
 
**✅ Output** *(verified by running — 64-bit system)*
```
int64
```
 
---
 
**▶️ Code Cell — Float Array**
```python
arr = np.array([10.5, 20.8, 30.4])
 
print(arr.dtype)
```
 
**✅ Output**
```
float64
```
 
---
 
**▶️ Code Cell — Boolean Array**
```python
arr = np.array([True, False, True])
 
print(arr.dtype)
```
 
**✅ Output**
```
bool
```
 
---
 
**▶️ Code Cell — String Array**
```python
arr = np.array(["HR", "IT", "Finance"])
 
print(arr.dtype)
```
 
**✅ Output**
```
<U7
```
 
📝 **Note:** Don't worry about `<U7` yet — just remember it means **Unicode String**. We'll break this notation down properly in a later chapter.
 
---
 
### 🔹 Mixed Data & Type Promotion
 
**📝 Concept**
When an array is created from mixed types, NumPy must pick **one** common dtype for the whole array — since it can only store one type at a time.
 
**▶️ Code Cell — Int + Float**
```python
arr = np.array([10, 20.5, 30])
 
print(arr)
print(arr.dtype)
```
 
**✅ Output** *(verified)*
```
[10.  20.5 30. ]
float64
```
 
💡 **Why?** Since one value is a float, every integer is **promoted to float** — NumPy can't mix types, so it upgrades everything to the "widest" common type.
 
---
 
**▶️ Code Cell — Int + Boolean**
```python
arr = np.array([10, True, 30])
 
print(arr)
print(arr.dtype)
```
 
**✅ Output** *(verified)*
```
[10  1 30]
int64
```
 
💡 **Why?** Internally, `True = 1` and `False = 0`. NumPy converts the boolean into an integer, so everything becomes `int64`.
 
---
 
**▶️ Code Cell — Int + String**
```python
arr = np.array([10, "20", 30])
 
print(arr)
print(arr.dtype)
```
 
**✅ Output** *(verified)*
```
['10' '20' '30']
<U21
```
 
💡 **Why?** A string can represent anything (numbers, text, etc.), but a number **cannot** represent arbitrary text. So NumPy converts *everything* to strings — the safest common type.
 
---
 
### 🔑 Rule — Type Promotion
 
> **NumPy always tries to find one common data type that can represent every element in the array.**
> This process is called **Type Promotion**.
 
**General hierarchy (weakest → strongest):** `bool → int → float → string`
(Whichever type appears, everything gets promoted *up* to that type — never down.)
 
---
 
### Key Takeaways — Chapter 3
 
- `.dtype` tells you the single fixed data type an array is using internally.
- Numeric arrays default to `int64` or `float64` on most 64-bit systems.
- String arrays show up as `<U#` (Unicode string of max length `#`).
- Mixing types triggers **Type Promotion** — NumPy converts everything to one common type:
  - `int + float → float`
  - `int + bool → int` (since `True/False` = `1/0`)
  - `int + string → string` (strings win over everything, since they're the most "general" type)

| dtype         | Meaning        |
| ------------- | -------------- |
| int8          | 8-bit Integer  |
| int16         | 16-bit Integer |
| int32         | 32-bit Integer |
| int64         | 64-bit Integer |
| float32       | 32-bit Float   |
| float64       | 64-bit Float   |
| bool          | Boolean        |
| str / Unicode | String         |


In [10]:
arr = np.array([5, 10, 15])

print(arr.dtype)

int64


In [11]:
arr = np.array([5, 10.5, 15])

print(arr.dtype)

float64


In [12]:
arr = np.array([5, 10.5, 15])

print(arr.dtype)

float64


In [13]:
arr = np.array([1, 2, 3], dtype=float)

print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


## Chapter 4: Array Attributes
 
Every `ndarray` carries metadata — information describing the array itself, not its actual values.
 
Think of it like an employee record:
 
```
Employee
├── Name
├── Age
├── Salary
└── Department
```
 
Similarly, every NumPy array has a set of built-in properties:
 
```
ndarray
├── shape
├── ndim
├── size
├── dtype
├── itemsize
└── nbytes
```
 
These attributes are used constantly in Data Engineering work.
 
### Sample Array
 
This array is used throughout the chapter.
 
```python
import numpy as np
 
employees = np.array([
    [101, 50000],
    [102, 62000],
    [103, 71000]
])
```
 
Output:
```
[[  101 50000]
 [  102 62000]
 [  103 71000]]
```
 
---
 
### 1. `shape`
 
Returns the dimensions of the array.
 
```python
print(employees.shape)
```
 
Output (verified):
```
(3, 2)
```
 
This means 3 rows and 2 columns — read as `(rows, columns)`.
 
For a one-dimensional array:
 
```python
a = np.array([10, 20, 30])
 
print(a.shape)
```
 
Output (verified):
```
(3,)
```
 
Note the trailing comma — this indicates a single dimension, not two.
 
---
 
### 2. `ndim`
 
Returns the number of dimensions.
 
```python
print(employees.ndim)
```
 
Output (verified):
```
2
```
 
`employees` has two dimensions — rows and columns.
 
```python
a = np.array([10, 20, 30])
 
print(a.ndim)
```
 
Output (verified):
```
1
```
 
---
 
### 3. `size`
 
Returns the total number of elements in the array.
 
```python
print(employees.size)
```
 
Output (verified):
```
6
```
 
The array holds six values in total: `101, 50000, 102, 62000, 103, 71000`.
 
---
 
### 4. `dtype`
 
Covered in Chapter 3 — returns the data type of the elements.
 
```python
print(employees.dtype)
```
 
Output (verified):
```
int64
```
 
---
 
### 5. `itemsize`
 
Returns the memory occupied by a single element, in bytes.
 
```python
print(employees.itemsize)
```
 
Output (verified):
```
8
```
 
Each integer occupies 8 bytes, since `int64` means 64 bits, and 64 bits ÷ 8 = 8 bytes.
 
---
 
### 6. `nbytes`
 
Returns the total memory occupied by the entire array.
 
Formula:
```
nbytes = size × itemsize
```
 
```python
print(employees.nbytes)
```
 
Output (verified):
```
48
```
 
This is `6 elements × 8 bytes = 48 bytes`.
 
---
 
### Summary — Chapter 4
 
| Attribute | Returns | Value for `employees` |
|---|---|---|
| `shape` | Dimensions as `(rows, columns)` | `(3, 2)` |
| `ndim` | Number of dimensions | `2` |
| `size` | Total number of elements | `6` |
| `dtype` | Data type of elements | `int64` |
| `itemsize` | Bytes per element | `8` |
| `nbytes` | Total bytes (`size × itemsize`) | `48` |
 
These six attributes together describe an array's structure, type, and memory footprint — essential for reasoning about performance in data pipelines.

In [19]:
import numpy as np

employees = np.array([
    [101,50000],
    [102,62000],
    [103,71000]
])

print("Shape :", employees.shape)
print("Dimensions :", employees.ndim)
print("Total Elements :", employees.size)
print("Data Type :", employees.dtype)
print("Bytes Per Element :", employees.itemsize)
print("Total Memory :", employees.nbytes)

Shape : (3, 2)
Dimensions : 2
Total Elements : 6
Data Type : int64
Bytes Per Element : 8
Total Memory : 48


# Precision:

Precision refers to the level of detail and accuracy with which numerical values are represented. NumPy data types have different levels of precision, which determine the range of values they can represent and the amount of memory they occupy.

In [14]:
 # Create an array with different data types
arr_int32 = np.array([1234567890, 1234567890], dtype=np.int32)
arr_int64 = np.array([1234567890, 1234567890], dtype=np.int64)

print("Data type of arr_int32:", arr_int32.dtype)   # Output: int32
print("Data type of arr_int64:", arr_int64.dtype)   # Output: int64

print(arr_int32)

# In this example, the `int32` data type has limited precision compared to `int64`, which can represent larger integers without loss of precision.

Data type of arr_int32: int32
Data type of arr_int64: int64
[1234567890 1234567890]


## **Impact of Precision on Memory Usage:**

In [15]:
# Create arrays with different data types
arr_float32 = np.array([1.1, 2.2, 3.3], dtype=np.float32)
arr_float64 = np.array([1.1, 2.2, 3.3], dtype=np.float64)

print("Memory usage of arr_float32:", arr_float32.itemsize * arr_float32.size, "bytes")  # Output: 12 bytes (3 elements * 4 bytes/element)
print("Memory usage of arr_float64:", arr_float64.itemsize * arr_float64.size, "bytes")  # Output: 24 bytes (3 elements * 8 bytes/element)
# In this 32 bit is less precise and 64 bit  is more precise

Memory usage of arr_float32: 12 bytes
Memory usage of arr_float64: 24 bytes


In [16]:
# Create a large array with float32 and float64 data types
large_array_float32 = np.arange(1000000, dtype=np.float32)
large_array_float64 = np.arange(1000000, dtype=np.float64)

# Calculate the sum of elements
sum_float32 = np.sum(large_array_float32)
sum_float64 = np.sum(large_array_float64)

print("Sum using float32:", sum_float32)
print("Sum using float64:", sum_float64) # this will is correct because higher precise will have the correct value it will have more space

Sum using float32: 499999800000.0
Sum using float64: 499999500000.0


## Chapter 5: Array Creation Methods
 
Instead of building arrays from Python lists every time,
 
```python
arr = np.array([1, 2, 3])
```
 
NumPy provides several helper functions for creating arrays directly. These are used routinely in Data Engineering, Machine Learning, and Scientific Computing.
 
---
 
### 1. `np.zeros()`
 
Creates an array filled entirely with zeros.
 
**One-dimensional:**
 
```python
import numpy as np
 
arr = np.zeros(5)
 
print(arr)
```
 
Output (verified):
```
[0. 0. 0. 0. 0.]
```
 
Note that the default data type is `float64`, even though no decimal values were specified.
 
**Two-dimensional:**
 
```python
arr = np.zeros((3, 4))
 
print(arr)
```
 
Output (verified):
```
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
```
 
This creates 3 rows and 4 columns.
 
**Specifying dtype:**
 
```python
arr = np.zeros((2, 3), dtype=int)
 
print(arr)
```
 
Output (verified):
```
[[0 0 0]
 [0 0 0]]
```
 
**When is this used?**
 
Suppose you're processing salary data for 1000 employees and need a bonus column that will be calculated later. Rather than appending values one at a time, you create the array upfront, filled with zeros as placeholders, and populate it afterward.
 
---
 
### 2. `np.ones()`
 
Works the same way as `np.zeros()`, but every element is set to one.
 
```python
arr = np.ones(5)
 
print(arr)
```
 
Output (verified):
```
[1. 1. 1. 1. 1.]
```
 
**Two-dimensional:**
 
```python
arr = np.ones((2, 4))
 
print(arr)
```
 
Output (verified):
```
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
```
 
**Specifying integer dtype:**
 
```python
arr = np.ones((3, 3), dtype=int)
 
print(arr)
```
 
Output (verified):
```
[[1 1 1]
 [1 1 1]
 [1 1 1]]
```
 
**Practical uses:** mask arrays, weight initialization, counters, and other cases where a default "active" or "starting" value of 1 is needed.
 
---
 
### 3. `np.empty()`
 
This function is commonly misunderstood. It does **not** create an array filled with zeros — it allocates memory without initializing the values.
 
```python
arr = np.empty((3, 3))
 
print(arr)
```
 
Output (verified on this system):
```
[[3.62734033e-315 0.00000000e+000 6.94012680e-310]
 [5.83038173e-317 6.94012680e-310 6.94012680e-310]
 [5.83661486e-317 3.62550786e-315 3.95252517e-322]]
```
 
The exact values will differ across machines and runs, since they are leftover data from whatever was previously stored in that memory location.
 
**Why use it?**
 
Initializing millions of values to zero takes time. If every value in the array is going to be overwritten immediately after creation, `np.empty()` skips that unnecessary initialization step and is faster.
 
---
 
### 4. `np.full()`
 
Creates an array filled with a single, specified value.
 
```python
arr = np.full(5, 100)
 
print(arr)
```
 
Output (verified):
```
[100 100 100 100 100]
```
 
**Two-dimensional:**
 
```python
arr = np.full((3, 4), 7)
 
print(arr)
```
 
Output (verified):
```
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
```
 
**Practical example**
 
Suppose every employee receives a fixed joining bonus of 5000. Rather than writing this out manually:
 
```python
[5000, 5000, 5000, ...]
```
 
it can be created directly:
 
```python
bonus = np.full(1000, 5000)
```
 
Output confirmed (first 5 values, shape):
```
[5000 5000 5000 5000 5000] (1000,)
```
 
---
 
### Summary — Chapter 5
 
| Function | Fills array with | Default dtype |
|---|---|---|
| `np.zeros(shape)` | `0` | `float64` |
| `np.ones(shape)` | `1` | `float64` |
| `np.empty(shape)` | Uninitialized (leftover memory) | `float64` |
| `np.full(shape, value)` | Given `value` | Matches type of `value` |
 
`np.empty()` trades predictability for speed — use it only when every element will be overwritten before being read.
 
---

In [20]:
import numpy as np

employees = 5

salary = np.zeros(employees)

bonus = np.full(employees,5000)

attendance = np.ones(employees)

print(salary)

print(bonus)

print(attendance)

[0. 0. 0. 0. 0.]
[5000 5000 5000 5000 5000]
[1. 1. 1. 1. 1.]


## Chapter 5: Array Creation Methods (Part 2)
 
### 1. `np.arange()`
 
This is NumPy's equivalent of Python's built-in `range()`, except it returns a NumPy array instead of a range object.
 
**Syntax:**
```python
np.arange(start, stop, step)
```
 
**Example 1:**
```python
import numpy as np
 
arr = np.arange(5)
print(arr)
```
 
Output (verified):
```
[0 1 2 3 4]
```
 
**Example 2:**
```python
arr = np.arange(10, 20)
print(arr)
```
 
Output (verified):
```
[10 11 12 13 14 15 16 17 18 19]
```
 
**Example 3:**
```python
arr = np.arange(10, 31, 5)
print(arr)
```
 
Output (verified):
```
[10 15 20 25 30]
```
 
**Example 4 — negative step:**
```python
arr = np.arange(10, 0, -2)
print(arr)
```
 
Output (verified):
```
[10  8  6  4  2]
```
 
**Data Engineering example — Employee IDs:**
```python
employee_ids = np.arange(1001, 1011)
print(employee_ids)
```
 
Output (verified):
```
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010]
```
 
---
 
### 2. `np.linspace()`
 
One of the more misunderstood functions. Unlike `arange()`, where you specify the step size, `linspace()` requires you to specify how many values you want in total.
 
**Syntax:**
```python
np.linspace(start, stop, number_of_values)
```
 
**Example:**
```python
arr = np.linspace(0, 10, 5)
print(arr)
```
 
Output (verified):
```
[ 0.   2.5  5.   7.5 10. ]
```
 
Exactly 5 values are returned, evenly spaced between 0 and 10 inclusive.
 
**Another example:**
```python
arr = np.linspace(100, 200, 11)
print(arr)
```
 
Output (verified):
```
[100. 110. 120. 130. 140. 150. 160. 170. 180. 190. 200.]
```
 
**Key difference:**
 
- `np.arange(0, 10, 2)` — gives values spaced 2 units apart.
- `np.linspace(0, 10, 6)` — divides the interval `[0, 10]` into 6 equally spaced values.
**When to use it:** most common in Machine Learning, simulations, graph plotting, and scientific computing. Less commonly used in ETL pipelines, where `arange()` is more typical.
 
---
 
### 3. `np.eye()`
 
Creates an identity matrix — a square matrix with 1s on the diagonal and 0s elsewhere.
 
```python
arr = np.eye(3)
print(arr)
```
 
Output (verified):
```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```
 
```python
arr = np.eye(4)
print(arr)
```
 
Output (verified):
```
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
```
 
**Rectangular matrix** — `eye()` can also create non-square matrices:
 
```python
arr = np.eye(3, 5)
print(arr)
```
 
Output (verified):
```
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
```
 
---
 
### 4. `np.identity()`
 
Very similar to `eye()`, but restricted to square matrices only.
 
```python
arr = np.identity(4)
print(arr)
```
 
Output (verified):
```
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
```
 
**Comparison:**
 
| `np.eye()` | `np.identity()` |
|---|---|
| Can create rectangular matrices | Only square matrices |
| More flexible | Simpler |
 
In practice, most developers default to `np.eye()` since it covers both cases.
 
---
 
### 5. `np.diag()`
 
Serves two purposes: creating a diagonal matrix from a list, or extracting the diagonal from an existing matrix.
 
**Creating a diagonal matrix:**
```python
arr = np.diag([10, 20, 30])
print(arr)
```
 
Output (verified):
```
[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]
```
 
**Extracting a diagonal:**
```python
matrix = np.array([
    [10, 2, 3],
    [4, 20, 6],
    [7, 8, 30]
])
print(np.diag(matrix))
```
 
Output (verified):
```
[10 20 30]
```
 
The same function behaves differently depending on whether the input is 1-D (builds a matrix) or 2-D (extracts the diagonal).
 
---
 
### 6. `np.asarray()`
 
Commonly used internally by other libraries.
 
```python
data = [10, 20, 30]
arr = np.asarray(data)
```
 
This looks identical to `np.array(data)`, so the distinction lies elsewhere.
 
**Key difference:**
 
- `np.array()` — creates a new array by default, even if the input is already an `ndarray`.
- `np.asarray()` — avoids copying if the input is already an `ndarray`.
**Example:**
```python
arr1 = np.array([1, 2, 3])
arr2 = np.asarray(arr1)
 
print(arr2, arr1 is arr2)
```
 
Output (verified):
```
[1 2 3] True
```
 
`arr1 is arr2` returns `True`, confirming no new array was created — `arr2` simply refers to the same object as `arr1`. This avoids unnecessary memory allocation and improves performance, which is why libraries such as Pandas, SciPy, and Scikit-learn use `np.asarray()` internally.
 
---
 
### Summary — Chapter 5
 
| Function | Purpose |
|---|---|
| `np.array()` | Create array from list/tuple |
| `np.zeros()` | Fill with zeros |
| `np.ones()` | Fill with ones |
| `np.empty()` | Uninitialized memory |
| `np.full()` | Fill with constant value |
| `np.arange()` | Evenly spaced values using step size |
| `np.linspace()` | Evenly spaced values using number of samples |
| `np.eye()` | Identity matrix (square or rectangular) |
| `np.identity()` | Square identity matrix only |
| `np.diag()` | Create or extract a diagonal |
| `np.asarray()` | Convert to ndarray without unnecessary copy |
 
---

## Chapter 6: Indexing
 
If array creation is about building arrays, indexing is about accessing the data inside them.
 
In Data Engineering, indexing is used constantly to:
- Retrieve specific values
- Access rows
- Access columns
- Modify values
- Inspect datasets
---
 
### 1-D Array Indexing
 
Start with a simple array:
 
```python
import numpy as np
 
salary = np.array([50000, 62000, 71000, 54000, 80000])
```
 
Memory layout, with positive index positions:
 
```
Index:   0       1       2       3       4
Value:   50000   62000   71000   54000   80000
```
 
**First element:**
```python
print(salary[0])
```
Output (verified):
```
50000
```
 
**Second element:**
```python
print(salary[1])
```
Output (verified):
```
62000
```
 
**Last element:**
```python
print(salary[4])
```
Output (verified):
```
80000
```
 
---
 
### Negative Indexing
 
Works exactly like Python lists — negative indices count backward from the end.
 
```
Value:      50000   62000   71000   54000   80000
Positive:      0       1       2       3       4
Negative:     -5      -4      -3      -2      -1
```
 
**Last element:**
```python
print(salary[-1])
```
Output (verified):
```
80000
```
 
**Second last:**
```python
print(salary[-2])
```
Output (verified):
```
54000
```
 
**Third last:**
```python
print(salary[-3])
```
Output (verified):
```
71000
```
 
---
 
### Updating Values
 
Arrays are mutable — values can be reassigned by index.
 
```python
salary[2] = 75000
 
print(salary)
```
 
Output (verified):
```
[50000 62000 75000 54000 80000]
```
 
**Data Engineering example — correcting one employee's attendance record:**
 
```python
attendance = np.array([95, 82, 91, 88, 97])
 
attendance[1] = 85
print(attendance)
```
 
Output (verified):
```
[95 85 91 88 97]
```
 
---
 
### 2-D Array Indexing
 
This is where indexing becomes genuinely useful.
 
```python
employees = np.array([
    [101, 50000],
    [102, 62000],
    [103, 71000],
    [104, 54000]
])
```
 
Visualized as a grid:
 
```
              Column 0    Column 1
Row 0         101         50000
Row 1         102         62000
Row 2         103         71000
Row 3         104         54000
```
 
**General syntax:**
```python
array[row, column]
```
 
NumPy prefers this comma-separated form over `array[row][column]`. Both work, but `array[row, column]` is faster and more idiomatic, since it performs a single indexing operation instead of two.
 
**Access the first employee's ID:**
```python
print(employees[0, 0])
```
Output (verified):
```
101
```
 
**First employee's salary:**
```python
print(employees[0, 1])
```
Output (verified):
```
50000
```
 
**Third employee's salary:**
```python
print(employees[2, 1])
```
Output (verified):
```
71000
```
 
**Last employee's salary:**
```python
print(employees[-1, -1])
```
Output (verified):
```
54000
```
 
**Modifying a value:**
```python
employees[1, 1] = 65000
 
print(employees)
```
Output (verified):
```
[[  101 50000]
 [  102 65000]
 [  103 71000]
 [  104 54000]]
```
 
**Accessing an entire row:**
```python
print(employees[1])
```
Output (verified):
```
[  102 65000]
```
 
The result is itself a 1-D `ndarray` — this is because a 2-D array is essentially a collection of 1-D arrays stacked together.
 
**First row:**
```python
print(employees[0])
```
Output (verified):
```
[  101 50000]
```
 
**Last row:**
```python
print(employees[-1])
```
Output (verified):
```
[  104 54000]
```
 
**Important observation:** rows can be accessed directly with a single index. Columns cannot — retrieving a full column requires slicing, which is covered in the next chapter.
 
---
 
### Common Mistakes
 
**Index out of bounds:**
```python
salary = np.array([10, 20, 30])
 
print(salary[5])
```
 
Error (verified):
```
IndexError: index 5 is out of bounds for axis 0 with size 3
```
 
**Invalid column index:**
```python
employees[0, 5]
```
 
Error (verified):
```
IndexError: index 5 is out of bounds for axis 1 with size 2
```
 
Always check that row and column indices stay within the bounds defined by the array's `shape` before indexing into it.
 
---
 
### Summary — Chapter 6
 
- 1-D arrays are indexed with a single value: `arr[i]`. Negative indices count from the end.
- 2-D arrays are indexed with `array[row, column]` — the preferred, faster form over `array[row][column]`.
- A single row index on a 2-D array returns a 1-D `ndarray`.
- Extracting a full column requires slicing (covered next).
- Indices outside the array's shape raise an `IndexError`.
---

In [24]:
import numpy as np

salary = np.array([50000, 62000, 71000, 54000, 80000])

employees = np.array([
    [101, 50000],
    [102, 62000],
    [103, 71000],
    [104, 54000],
    [105, 80000]
])

print(salary)
print()
print(employees)

[50000 62000 71000 54000 80000]

[[  101 50000]
 [  102 62000]
 [  103 71000]
 [  104 54000]
 [  105 80000]]


## Indexing types

In [22]:
print("First Salary :", salary[0])

print("Second Salary :", salary[1])

print("Third Salary :", salary[2])

print("Fourth Salary :", salary[3])

print("Last Salary :", salary[4])

First Salary : 50000
Second Salary : 62000
Third Salary : 71000
Fourth Salary : 54000
Last Salary : 80000


In [23]:
print("Last Salary :", salary[-1])

print("Second Last :", salary[-2])

print("Third Last :", salary[-3])

print("First :", salary[-5])

Last Salary : 80000
Second Last : 54000
Third Last : 71000
First : 50000


In [26]:
print("Before")

print(salary)

salary[2] = 75000

print()

print("After")

print(salary)

Before
[50000 62000 71000 54000 80000]

After
[50000 62000 75000 54000 80000]


## Access Every Employee Row
- Observe that each row is itself a NumPy array.

In [27]:
print(employees[0])

print(employees[1])

print(employees[2])

print(employees[3])

print(employees[4])

[  101 50000]
[  102 62000]
[  103 71000]
[  104 54000]
[  105 80000]


In [28]:
print("Employee ID :", employees[0,0])

print("Salary :", employees[0,1])

print()

print("Employee ID :", employees[2,0])

print("Salary :", employees[2,1])

print()

print("Employee ID :", employees[4,0])

print("Salary :", employees[4,1])

Employee ID : 101
Salary : 50000

Employee ID : 103
Salary : 71000

Employee ID : 105
Salary : 80000


In [29]:
print(employees[-1,-1])

print(employees[-1,0])

print(employees[-2,-1])

print(employees[-3,0])

80000
105
54000
103


## Update Employee Salary

In [30]:
print("Before")

print(employees)

employees[1,1] = 65000

employees[4,1] = 90000

print()

print("After")

print(employees)

Before
[[  101 50000]
 [  102 62000]
 [  103 71000]
 [  104 54000]
 [  105 80000]]

After
[[  101 50000]
 [  102 65000]
 [  103 71000]
 [  104 54000]
 [  105 90000]]


## Check Returned Types

Notice the difference between:

- Entire array
- Row
- Individual value

In [31]:
print(type(employees))

print(type(employees[0]))

print(type(employees[0,0]))

print(type(employees[0,1]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [32]:
employee_ids = np.array([101,102,103,104,105])

salary = np.array([50000,62000,71000,54000,80000])

attendance = np.array([95,88,97,91,84])

print("Employee :", employee_ids[2])

print("Salary :", salary[2])

print("Attendance :", attendance[2])

Employee : 103
Salary : 71000
Attendance : 97


## Chapter 7: Slicing

- If indexing gives you one element, slicing gives you multiple elements.

- This is one of the most frequently used features in Data Engineering because you rarely work with a single value—you usually work with rows, columns, or subsets of data.

In [2]:
import numpy as np

salary = np.array([50000, 62000, 71000, 54000, 80000, 90000])

employees = np.array([
    [101, 50000],
    [102, 62000],
    [103, 71000],
    [104, 54000],
    [105, 80000],
    [106, 90000]
])

print(salary)

print()

print(employees)

[50000 62000 71000 54000 80000 90000]

[[  101 50000]
 [  102 62000]
 [  103 71000]
 [  104 54000]
 [  105 80000]
 [  106 90000]]


## Slice Syntax

```python
array[start : stop : step]
```
Remember:

- start → Included
- stop → Excluded
- step → Increment

In [6]:
# First Three Salaries
print(salary[0:3])

# Middle Salaries
print(salary[2:5])

# From Beginning
print(salary[:4])

# Till End
print(salary[3:])

# Entire Array
print(salary[:])

# Every Alternate Element
print(salary[::2])

# Skip Two Elements
print(salary[::3])

# Reverse Array
print(salary[::-1])

# Reverse Alternate
print(salary[::-2])

[50000 62000 71000]
[71000 54000 80000]
[50000 62000 71000 54000]
[54000 80000 90000]
[50000 62000 71000 54000 80000 90000]
[50000 71000 80000]
[50000 54000]
[90000 80000 54000 71000 62000 50000]
[90000 54000 62000]


## 2D Slicing

General Syntax

```python
array[row_slice, column_slice]
```

- This is one of the biggest advantages of NumPy over Python lists.

In [7]:
# First Three Rows
print(employees[0:3])

# Last Three Rows
print(employees[3:])

[[  101 50000]
 [  102 62000]
 [  103 71000]]
[[  104 54000]
 [  105 80000]
 [  106 90000]]


## Understanding NumPy 2D Array Slicing

When you have a 2D NumPy array (rows and columns), you can access specific rows, columns, or sub-blocks using this general syntax:

    array[row_selector, column_selector]

- The part **before the comma** controls which **rows** you select.
- The part **after the comma** controls which **columns** you select.
- A colon `:` alone means "give me everything" (all rows, or all columns).

### Common patterns

| Syntax | Meaning |
|---|---|
| `array[:, 0]` | All rows, only column 0 |
| `array[:, 1]` | All rows, only column 1 |
| `array[:2, :]` | Rows 0 and 1 (index 2 excluded), all columns |
| `array[:2, 0]` | Rows 0 and 1, only column 0 |
| `array[-3:, :]` | Last 3 rows, all columns |
| `array[::2]` | Every 2nd row (step = 2), all columns |
| `array[::-1]` | All rows, reversed order |
| `array[1:4, :]` | Rows 1, 2, 3 (index 4 excluded), all columns |
| `array[0:2, 0:2]` | Rows 0-1 AND columns 0-1 → a sub-block |
| `array[1:, 1:]` | All rows from index 1 onward AND all columns from index 1 onward |

### Key rules to remember

1. **Slicing is `start:stop:step`** — `stop` is always **excluded**. So `[1:4]` gives indices 1, 2, 3 — not 4.
2. **Negative indices count from the end.** `-1` is the last row, `-3` is the third-from-last row.
3. **Leaving a number blank** means "go to the start" or "go to the end" — e.g. `[2:]` means "from index 2 to the end", `[:3]` means "from the start up to (not including) index 3".
4. **A single column index (like `[:, 0]`)** returns a flattened 1D array, while a **range (like `[:, 0:1]`)** keeps it as a 2D column — this is an important distinction to notice.
5. Combining a row slice and a column slice at the same time (`array[row_slice, col_slice]`) lets you pull out a **rectangular sub-matrix** in one step.

Once you're comfortable with this pattern, all the slicing examples below will make a lot more sense.

## First Column (Employee IDs)
- Using `[:, 0]` selects all rows and only the first column (index 0), which gives us just the Employee IDs.

In [9]:
print(employees[:,0])

[101 102 103 104 105 106]


### Second Column (Salary)

`[:, 1]` selects all rows and the second column (index 1). Imagine this is a salary column from a CSV file.

In [10]:
print(employees[:,1])

[50000 62000 71000 54000 80000 90000]


- Imagine this is a salary column from a CSV file.

###  First Two Rows, Both Columns

`[:2, :]` slices the first two rows and keeps all columns.

In [11]:
print(employees[:2,:])

[[  101 50000]
 [  102 62000]]


### First Two Rows, First Column

`[:2, 0]` slices the first two rows and keeps only the first column (Employee ID).

In [12]:
print(employees[:2,0])

[101 102]


###  First Two Rows, Second Column

`[:2, 1]` slices the first two rows and keeps only the second column (Salary).

In [14]:
print(employees[:2,1])

[50000 62000]


### Last Three Employee IDs

`[-3:, 0]` uses negative indexing to grab the last three rows, then the first column.

### Last Three Salaries

`[-3:, 1]` grabs the last three rows and the second column (Salary).

In [15]:
print(employees[-3:,1])

[54000 80000 90000]


### Every Alternate Row

`[::2]` uses a step of 2 to select every other row, starting from row 0.

In [16]:
print(employees[::2])

[[  101 50000]
 [  103 71000]
 [  105 80000]]


### Reverse Rows

`[::-1]` uses a step of -1 to reverse the order of the rows.

In [17]:
print(employees[::-1])

[[  106 90000]
 [  105 80000]
 [  104 54000]
 [  103 71000]
 [  102 62000]
 [  101 50000]]


### Extract Submatrix

`[1:4, :]` slices rows at index 1 through 3 (row 4 excluded) and keeps all columns.

In [18]:
print(employees[1:4,:])

[[  102 62000]
 [  103 71000]
 [  104 54000]]


### Another Submatrix

`[2:5, :]` slices rows at index 2 through 4 (row 5 excluded) and keeps all columns.

In [19]:
print(employees[2:5,:])

[[  103 71000]
 [  104 54000]
 [  105 80000]]


### Slice Both Rows and Columns

Let's switch to a fresh 3x3 `matrix` to practice slicing rows and columns together.

In [20]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Now try `matrix[0:2, 0:2]` — this slices the top-left 2x2 block: rows 0-1 and columns 0-1.

In [21]:
print(matrix[0:2, 0:2])

[[1 2]
 [4 5]]


In [22]:
print(matrix[1:,1:])

[[5 6]
 [8 9]]


# NumPy - Chapter 8: Boolean Indexing

## What is Boolean Indexing?

Boolean Indexing filters data using Boolean (`True` / `False`) arrays.

---

## Comparison Operators

```python
>
<
>=
<=
==
!=
```

---

## Examples

```python
salary[salary > 60000]

attendance[attendance >= 90]
```

---

## Logical Operators

AND

```python
&
```

OR

```python
|
```

NOT

```python
~
```

Always wrap each condition in parentheses.

```python
(salary > 60000) & (attendance > 90)
```

---

## Filtering Rows in 2D Arrays

```python
employees[employees[:,1] > 60000]
```

---

## Updating with Boolean Indexing

```python
salary[salary < 60000] += 5000
```

---

## Key Takeaways

- Boolean Indexing is NumPy's equivalent of SQL's `WHERE` clause.
- Comparisons create Boolean masks.
- Boolean masks can filter values or entire rows.
- Boolean Indexing can also modify data efficiently.

### Sample Dataset

In [23]:
import numpy as np

employee_ids = np.array([101, 102, 103, 104, 105, 106])

salary = np.array([50000, 62000, 71000, 54000, 80000, 90000])

attendance = np.array([95, 88, 97, 91, 84, 99])

### Understanding Boolean Arrays

Suppose we ask:
Which employees have salary greater than 60000?

In [24]:
print(salary > 60000)

[False  True  True False  True  True]


Output

    [False  True  True False  True  True]

Notice something interesting.
NumPy didn't return the salaries.
It returned a Boolean array.

    Salary

    50000   -> False
    62000   -> True
    71000   -> True
    54000   -> False
    80000   -> True
    90000   -> True

This Boolean array is called a mask.

### Filter the Values

Now use the mask.

In [25]:
print(salary[salary > 60000])

[62000 71000 80000 90000]


Output

    [62000 71000 80000 90000]

Think of it as

    salary
    ↓
    Boolean Mask
    ↓
    Filtered Result

### Employees with Salary > 60000

In [26]:
print(employee_ids[salary > 60000])

[102 103 105 106]


Output

    [102 103 105 106]

Notice
The condition was applied on salary, but we retrieved employee IDs.
This is extremely common in analytics.

### Attendance ≥ 90

In [27]:
print(attendance >= 90)

[ True False  True  True False  True]


Output

    [ True False  True  True False  True]

Now filter

In [28]:
print(attendance[attendance >= 90])

[95 97 91 99]


Output

    [95 97 91 99]

### Employee IDs with Good Attendance

In [29]:
print(employee_ids[attendance >= 90])

[101 103 104 106]


### Less Than

In [30]:
print(salary[salary < 70000])

[50000 62000 54000]


### Equal To

In [31]:
print(salary[salary == 71000])

[71000]


### Not Equal

In [32]:
print(salary[salary != 71000])

[50000 62000 54000 80000 90000]


### Logical AND

Employees with
Salary > 60000
AND
Attendance > 90

In [33]:
mask = (salary > 60000) & (attendance > 90)

print(mask)

[False False  True False False  True]


Output

    [False False  True False False  True]

Now retrieve employee IDs

In [34]:
print(employee_ids[mask])

[103 106]


### Directly

In [35]:
print(employee_ids[(salary > 60000) & (attendance > 90)])

[103 106]


### Logical OR

Salary greater than 80000
OR
Attendance greater than 95

In [36]:
mask = (salary > 80000) | (attendance > 95)

print(mask)

[False False  True False False  True]


In [37]:
print(employee_ids[mask])

[103 106]


### Logical NOT

In [38]:
mask = ~(attendance >= 90)

print(mask)

[False  True False False  True False]


In [39]:
print(employee_ids[mask])

[102 105]


### Between Two Values

Employees earning between
60000
and
85000

In [40]:
mask = (salary >= 60000) & (salary <= 85000)

print(salary[mask])

[62000 71000 80000]


### Modify Using Boolean Indexing

Increase salary by 5000
for everyone earning less than 60000.

In [41]:
salary[salary < 60000] += 5000

print(salary)

[55000 62000 71000 59000 80000 90000]


### 2D Boolean Indexing

In [42]:
employees = np.array([
    [101,50000],
    [102,62000],
    [103,71000],
    [104,54000],
    [105,80000],
    [106,90000]
])

print(employees)

[[  101 50000]
 [  102 62000]
 [  103 71000]
 [  104 54000]
 [  105 80000]
 [  106 90000]]


## Filter rows

In [43]:
print(employees[employees[:,1] > 60000])

[[  102 62000]
 [  103 71000]
 [  105 80000]
 [  106 90000]]


Output

    [[  102 62000]
     [  103 71000]
     [  105 80000]
     [  106 90000]]

This is one of the most useful patterns in NumPy.

Notice

    employees[:,1]

means
Salary column.

### Employees with Salary > 70000

In [44]:
high_salary = employees[employees[:,1] > 70000]

print(high_salary)

[[  103 71000]
 [  105 80000]
 [  106 90000]]


### Practical Data Engineering Example

Suppose invalid attendance
means attendance < 90

In [45]:
attendance = np.array([95,88,97,91,84,99])

valid_attendance = attendance[attendance >= 90]

print(valid_attendance)

[95 97 91 99]


Output

    [95 97 91 99]

This is exactly how data cleaning pipelines remove invalid records.

In [48]:
import numpy as np

attendance = np.array([95, 88, 97, 91, 84, 99])

invalid = attendance[attendance < 80]

print(invalid)

[]


In [49]:
print(type(invalid))

<class 'numpy.ndarray'>


# NumPy - Boolean Indexing: Empty Arrays

## Does Boolean Indexing Raise an Error if No Elements Match?

**No.**

Boolean indexing **does not raise an error** if no elements satisfy the condition.

Instead, NumPy returns an **empty ndarray**.

---

## Example

```python
import numpy as np

attendance = np.array([95, 88, 97, 91, 84, 99])

invalid = attendance[attendance < 80]

print(invalid)
```

### Output

```python
[]
```

---

## Why?

First, NumPy evaluates the condition.

```python
attendance < 80
```

Result:

```python
[False False False False False False]
```

Since every value is `False`, there are **no matching elements**.

NumPy simply returns an empty array.

```python
[]
```

No exception is raised.

---

## Type of the Result

```python
print(type(invalid))
```

Output

```python
<class 'numpy.ndarray'>
```

Even though it is empty, it is still a valid NumPy array.

---

## Size of the Result

```python
print(invalid.size)
```

Output

```python
0
```

or

```python
print(len(invalid))
```

Output

```python
0
```

---

## Why Doesn't NumPy Raise an Error?

Boolean indexing is a **filtering operation**, similar to SQL.

SQL Example:

```sql
SELECT *
FROM employees
WHERE salary > 1000000;
```

If no employee satisfies the condition, SQL returns:

```
0 Rows
```

It does **not** raise an error.

NumPy follows the same behavior.

---

## When Does an Error Occur?

An error occurs **only when you try to access an element that doesn't exist.**

Example:

```python
invalid = attendance[attendance < 80]

print(invalid)
```

Output

```python
[]
```

No error.

But,

```python
print(invalid[0])
```

Output

```text
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Reason:

The array contains **zero elements**, so index `0` does not exist.

---

## Safe Way

Always check whether the array contains any elements before accessing them.

```python
if invalid.size > 0:
    print(invalid[0])
else:
    print("No invalid attendance records found.")
```

Output

```text
No invalid attendance records found.
```

---

## Real Data Engineering Example

```python
invalid_salary = salary[salary < 0]
```

If there are no negative salaries,

```python
print(invalid_salary)
```

Output

```python
[]
```

This simply means the dataset contains **no invalid salary records**, and the ETL pipeline can continue safely.

---

## Key Takeaways

- Boolean indexing returns a **NumPy array**.
- If no elements match the condition, NumPy returns an **empty ndarray (`[]`)**.
- No exception is raised during filtering.
- An `IndexError` occurs **only when accessing an element** from an empty array.
- Always check `array.size > 0` before accessing elements if the result may be empty.
- This behavior makes Boolean indexing ideal for filtering operations in ETL and data engineering pipelines.

# NumPy - Chapter 9: Fancy Indexing

## What is Fancy Indexing?

Fancy Indexing allows selecting elements or rows using a list (or array) of indices instead of a single index or slice.

So far, we've accessed data using:

- A single index (`arr[2]`)
- A slice (`arr[1:4]`)
- A Boolean condition (`arr[arr > 50]`)

But what if you want specific elements that are not consecutive?

For example:
- Employee at index 0
- Employee at index 3
- Employee at index 5

You can't do that with slicing.
That's where Fancy Indexing comes in.

---

## 1D Fancy Indexing

```python
arr[[0,2,5]]
```

Selects elements at indices `0`, `2`, and `5`.

---

## Reordering

```python
arr[[5,3,1]]
```

Returns elements in the specified order.

---

## Duplicates

```python
arr[[1,1,3]]
```

Indices can be repeated.

---

## 2D Fancy Indexing

### Select Multiple Rows

```python
arr[[0,2,5]]
```

---

### Select Individual Elements

```python
rows = [0,2,5]
cols = [1,1,1]

arr[rows, cols]
```

NumPy pairs the indices element-wise:

- `(0,1)`
- `(2,1)`
- `(5,1)`

---

## Fancy Indexing vs Slicing

### Slicing

```python
arr[1:5]
```

Returns a continuous range.

### Fancy Indexing

```python
arr[[1,4,5]]
```

Returns elements from arbitrary positions.

---

## Common Data Engineering Uses

- Selecting random samples
- Train/Test split
- Mini-batch creation
- Reordering records
- Extracting specific rows

---

## Key Takeaways

- Fancy Indexing uses lists or arrays of indices.
- Indices can be in any order.
- Indices can be repeated.
- Works for both 1D and 2D arrays.
- Useful for selecting arbitrary records without loops.

### Sample Data

In [1]:
import numpy as np

employee_ids = np.array([101, 102, 103, 104, 105, 106])

salary = np.array([50000, 62000, 71000, 54000, 80000, 90000])

print(employee_ids)
print(salary)

[101 102 103 104 105 106]
[50000 62000 71000 54000 80000 90000]


### Select Multiple Elements

In [2]:
print(employee_ids[[0, 2, 5]])

[101 103 106]


Output

    [101 103 106]

Notice
Instead of giving one index, we give a list of indices.

    employee_ids[[0,2,5]]

### Select Salaries

In [3]:
print(salary[[1, 3, 4]])

[62000 54000 80000]


### Reorder Data

Fancy indexing can also reorder data.

In [4]:
print(employee_ids[[5,4,3,2,1,0]])

[106 105 104 103 102 101]


Output

    [106 105 104 103 102 101]

Notice this is not reversing the array using slicing—it is explicitly selecting indices in a custom order.

In [5]:
print(employee_ids)
print(type(employee_ids))

[101 102 103 104 105 106]
<class 'numpy.ndarray'>


### Duplicate Elements

Indices can repeat.

### Random Order
- This is commonly used after shuffling data.

In [6]:
indices = [4, 1, 5, 0]

print(employee_ids[indices])

[105 102 106 101]


### Fancy Indexing on 2D Arrays

Create a dataset.

In [7]:
employees = np.array([
    [101,50000],
    [102,62000],
    [103,71000],
    [104,54000],
    [105,80000],
    [106,90000]
])

print(employees)

[[  101 50000]
 [  102 62000]
 [  103 71000]
 [  104 54000]
 [  105 80000]
 [  106 90000]]


### Select Multiple Rows

In [8]:
print(employees[[0,2,5]])

[[  101 50000]
 [  103 71000]
 [  106 90000]]


### Custom Row Order

In [9]:
print(employees[[5,1,3]])

[[  106 90000]
 [  102 62000]
 [  104 54000]]


### Duplicate Rows

In [10]:
print(employees[[2,2,4]])

[[  103 71000]
 [  103 71000]
 [  105 80000]]


### Advanced Fancy Indexing

Suppose you want

    employees[0,1]
    employees[2,1]
    employees[5,1]

Instead of writing three separate statements,
use Fancy Indexing.

In [11]:
rows = [0,2,5]

cols = [1,1,1]

print(employees[rows, cols])

[50000 71000 90000]


Output

    [50000 71000 90000]

Explanation
NumPy pairs the indices element by element.

    (0,1)
    (2,1)
    (5,1)

### Fancy Indexing vs Slicing

Slicing

In [12]:
print(employee_ids[1:5])

[102 103 104 105]


Output

    [102 103 104 105]

Continuous range.

Fancy Indexing

In [13]:
print(employee_ids[[1,4,5]])

[102 105 106]


Output

    [102 105 106]

Custom positions.

### Data Engineering Example

Suppose after preprocessing, your ML model wants only these rows:

    0
    4
    5

Instead of looping,

Output

    [[  101 50000]
     [  105 80000]
     [  106 90000]]

This is commonly used for:

- Train/Test split
- Random sampling
- Batch creation
- Cross-validation
- Selecting specific records

## Challenge

Use the following array:

In [14]:
employees = np.array([
    [101,50000],
    [102,62000],
    [103,71000],
    [104,54000],
    [105,80000],
    [106,90000]
])

## Q1) Print employee IDs at indices
- 1
- 3
- 5

In [23]:
print(employees[[1,3,5],[0,0,0]])

[102 104 106]


## Q2) Print rows 
- 1
- 3
- 5

In [18]:
print(employees[[1,3,5]])

[[  102 62000]
 [  104 54000]
 [  106 90000]]


## Q3) Print salaries of employees
-101
- 104
- 106

In [20]:
print(employees[[1,3,5],[1,1,1]])

[62000 54000 90000]


## Q4) Duplicate the second row three times.

In [24]:
print(employees[[2,2,2]])

[[  103 71000]
 [  103 71000]
 [  103 71000]]
